# Generated by Django 3.1.5 on 2021-01-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha2code', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('capital', models.CharField(max_length=264, unique=True)),
                ('population', models.BigIntegerField()),
                ('timezones', models.CharField(max_length=264)),
                ('language', models.CharField(max_length=264)),
                ('neighbour', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=264)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbour', models.CharField(max_length=264)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
